<a href="https://colab.research.google.com/github/Martin26H/Manipulacion-y-Transformacion-de-Datos-con-Pandas-y-NumPy/blob/master/Manipulaci%C3%B3n_y_Transformaci%C3%B3n_de_Datos_con_Pandas_y_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
 arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]

1

In [ ]:
arr[1]

2

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[0,2]

3

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:3]

array([1, 2, 3])

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
arr[-1]

9

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

#Tipos de Datos

In [ ]:
arr2 = np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr2 = np.array([1,2,3,4], dtype='float64')
arr2.dtype

dtype('float64')

In [ ]:
arr2

array([1, 2, 3, 4])

In [ ]:
arr2 = arr2.astype(np.float64)
arr2

array([1., 2., 3., 4.])

#Dimensiones

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz2 = np.array([[1,2,3],[4,5,6]])
print(matriz2)
matriz2.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
Tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(Tensor)
Tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

Agregar o eliminar dimensiones

In [ ]:
vector2 = np.array([1,2,3], ndmin=10)
print(vector2)
vector2.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector2, vector2.ndim)
vector3 = np.squeeze(vector2)
print(vector3, vector3.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Creando arrays

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.3126639757822637

In [ ]:
np.random.rand(4)

array([0.68873222, 0.25616086, 0.41829175, 0.05179589])

In [ ]:
np.random.rand(4,4)

array([[0.0503547 , 0.65095744, 0.29784162, 0.84605572],
       [0.73981276, 0.3965973 , 0.2814317 , 0.21407552],
       [0.59765877, 0.74875001, 0.00397263, 0.37724808],
       [0.88927848, 0.24595232, 0.84204133, 0.65180495]])

In [ ]:
np.random.randint(1,15)

13

In [ ]:
np.random.randint(1,100,(10,10))

array([[23, 54, 35, 43, 86, 25, 63, 60, 65, 81],
       [78, 19, 71, 34, 21, 15, 55, 17, 86, 27],
       [99, 95, 17, 56, 62, 63, 48, 59, 61, 29],
       [92, 86, 90, 30, 69, 56, 98,  2, 65, 41],
       [91,  2,  8, 69, 60, 40, 45,  1,  6, 47],
       [45, 97, 93, 81, 32, 40, 26, 39, 88, 10],
       [23, 76, 45, 70, 69, 50, 94, 18, 26, 27],
       [45, 54, 42, 81, 81, 66, 91, 57, 67, 27],
       [74, 48, 28, 19, 89, 83, 66, 58, 29, 20],
       [14, 78, 25, 85, 31, 37, 48, 85, 53, 41]])

##Shape y Reshape

In [ ]:
arr3 = np.random.randint(1,10,(3,2))

In [ ]:
arr3.shape

(3, 2)

In [ ]:
arr3

array([[4, 4],
       [5, 4],
       [9, 3]])

In [ ]:
arr3.reshape(1,6)

array([[4, 4, 5, 4, 9, 3]])

In [ ]:
arr3.reshape(2,3)

array([[4, 4, 5],
       [4, 9, 3]])

In [ ]:
np.reshape(arr3,(1,6))

array([[4, 4, 5, 4, 9, 3]])

In [ ]:
arr3

array([[4, 4],
       [5, 4],
       [9, 3]])

In [ ]:
np.reshape(arr3,(2,3),'C')

array([[4, 4, 5],
       [4, 9, 3]])

In [ ]:
np.reshape(arr3,(2,3),'F')

array([[4, 9, 4],
       [5, 4, 3]])

In [ ]:
np.reshape(arr3,(2,3),'A')

array([[4, 4, 5],
       [4, 9, 3]])

In [ ]:
matriz3 = np.random.randint(1,20,(5,4))
matriz3


array([[ 1, 14, 19, 15],
       [15, 11,  2, 19],
       [ 2,  8,  8, 11],
       [ 5,  2,  1, 14],
       [ 5,  6, 12, 14]])

In [ ]:
np.reshape(matriz3,(4,5),'C')

array([[ 1, 14, 19, 15, 15],
       [11,  2, 19,  2,  8],
       [ 8, 11,  5,  2,  1],
       [14,  5,  6, 12, 14]])

## Funciones principales de Numpy

In [ ]:
arr4 = np.random.randint(1,20,10)

In [ ]:
matriz4 = arr4.reshape(2,5)
matriz4

array([[ 7,  2,  9,  1, 15],
       [18,  1, 14, 14, 16]])

In [ ]:
matriz4.max(0)

array([18,  2, 14, 14, 16])

In [ ]:
arr4.argmax()

5

In [ ]:
matriz4.argmax(0)

array([1, 0, 1, 1, 1])

In [ ]:
arr4.min()

1

In [ ]:
matriz4.min(0)

array([ 7,  1,  9,  1, 15])

In [ ]:
 matriz4.argmin(0)

array([0, 1, 0, 0, 0])

In [ ]:
arr4

array([ 7,  2,  9,  1, 15, 18,  1, 14, 14, 16])

In [ ]:
arr4.ptp()

17

In [ ]:
matriz4.ptp(0)

array([11,  1,  5, 13,  1])

In [ ]:
np.percentile(arr4,50)

11.5

In [ ]:
arr4.sort()
arr4

array([ 1,  1,  2,  7,  9, 14, 14, 15, 16, 18])

In [ ]:
np.median(arr4)

11.5

In [ ]:
np.mean(arr4)

9.7

In [ ]:
np.std(arr4)

6.261788881781308

In [ ]:
np.var(arr4)

39.21

In [ ]:
a.ndim
b.ndim

1

In [ ]:
b = np.expand_dims(b,axis=0)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Copy

In [ ]:
arr5 = np.arange(0,11)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_de_arr5 = arr5[0:6]

In [ ]:
trozo_de_arr5[:] = 0
trozo_de_arr5

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr5

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr5_copy = arr5.copy()

In [ ]:
arr5_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr5_copy[:] = 100

In [ ]:
arr5_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr5

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Condiciones

In [3]:
arr6 = np.linspace(1,10,10, dtype='int8' )
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
indices_cond = arr6 > 5 
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
arr6[(arr6>5) & (arr6<9)]

array([6, 7, 8], dtype=int8)

## Operaciones

In [6]:
lista2 =  [1,2]
lista2

[1, 2]

In [7]:
lista2 * 2

[1, 2, 1, 2]

In [8]:
arr7 = np.arange(0,10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr8 = arr7.copy()

In [11]:
arr7 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1 / arr7

<ipython-input-13-2fefbe9810fb>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr7


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr7 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
arr7 + arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])